### ISSUE TITLE
Social Network Issue

### ISSUE THREAD

**Issue by ChillyCurve** [BesrourMS/hold#1]
First off, thank you so much for your work on this theme. I have spent the past week customizing/admiring it.

I am having a small issue with the social media icons. The links do not work out of the box, but if I inspect element on my site and select the div, then they magically start working.

Can't figure it out, thanks in advance.

**Comment by BesrourMS** [comment]
Hi @ChillyCurve 
Send me your website link maybe I can find the problem.

**Comment by ChillyCurve** [comment]
url redacted
Thanks in advance

I couldn't find a private message function...? Is there one?

**Comment by BesrourMS** [comment]
Hi @ChillyCurve 
in line 178 change 
`<div class="container">` by `<div class="col-md-12">`  and that's it
Isn't It Magic :)

**Comment by ChillyCurve** [comment]
That did it! Thanks
